test_name: Articles API Usage

stages:

  - name: Try to post an article without authenticating
    request:
      url: http://localhost:3000/articles/new
      json:
        title: "Test article"
        content: "This is a test article. The contents is for testing only."
        author: "David Feinzimer"
        article_date: 03/10/2019
      method: POST
    response:
      status_code: 401

  - name: Try to post an article using the wrong password
      url: http://localhost:3000/articles/new
      auth:
        - dfeinzimer@gmail.com
        - abc123wrongpass
      json:
        title: "Test article 2"
        content: "This is a test article. The contents is for testing only."
        author: "David Feinzimer"
        article_date: 03/15/2019
      method: POST
    response:
      status_code: 401

  - name: Post an article successfully
      url: http://localhost:3000/articles/new
      auth:
        - dfeinzimer@gmail.com
        - abc123
      json:
        title: "Test article 3"
        content: "This is a test article. The contents is for testing only."
        author: "David Feinzimer"
        article_date: 03/15/2019
      method: POST
    response:
      status_code: 201

  - name: Retrieve the newly posted article
    request:
      url: http://localhost:3000/articles/recent/1
      method: GET
    response:
      status_code: 200

  - name: Check that the newly posted article is the most recent
    request:
      url: http://localhost:3000/articles/recent/meta/1
      method: GET
    response:
      status_code: 200
