test_name: Users API Usage
stages:
  - name: Try to change the password for a user that does not exist
    request:
      url: http://localhost:3003/users/
      method: GET
    response:
      status_code: 200
      body:
        id: 1
  - name: Create a user
    request:
      url: http://localhost:3003/users/
      method: GET
    response:
      status_code: 200
      body:
        id: 1
  - name: Change the user’s password
    request:
      url: http://localhost:3003/users/
      method: GET
    response:
      status_code: 200
      body:
        id: 1
  - name: Delete the user
    request:
      url: http://localhost:3003/users/
      method: GET
    response:
      status_code: 200
      body:
        id: 1
  - name: Try to change the password for the deleted user
    request:
      url: http://localhost:3003/users/
      method: GET
    response:
      status_code: 200
      body:
        id: 1
