test_name: Users API Usage
stages:
  
  - name: Create a user
    request:
      url: http://localhost:3003/users
      json:
        email: miggle@gmail.com
        display_name": mgl 
        password": abc123
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201
      headers:
        content-type: text/html; charset=utf-8
      connection: close
      server: Werkzeug/0.14.1 Python/3.6.7
      date:
